{% set name = "sqlalchemy-migrate" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cfada30bbcf79a83b3a2d1bcd637de7e1f43e390d54de33e4f3249fd9aacfae

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
    - pbr
  run:
    - python
    - pbr
    - sqlalchemy
    - decorator
    - six
    - sqlparse
    - tempita

test:
  imports:
    - migrate

about:
  home: https://github.com/openstack/sqlalchemy-migrate
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Database schema migration for SQLAlchemy'

  description: |
    Inspired by Ruby on Rails' migrations, Migrate provides a way to deal with
    database schema changes in SQLAlchemy projects.

    Migrate extends SQLAlchemy to have database changeset handling. It provides
    a database change repository mechanism which can be used from the command
    line as well as from inside python code.
  doc_url: https://sqlalchemy-migrate.readthedocs.io/en/latest/
  dev_url: https://github.com/openstack/sqlalchemy-migrate

extra:
  recipe-maintainers:
    - mariusvniekerk
