travis:
  secure:
    BINSTAR_TOKEN: HSRdXQFtgjuff5BuHyNNV8fNxllGcwGbRj61qKN21LPKUsXkZurLKThh9mPhi4vP0HuI5I2JqqAD85N/ZM0rcmwn9CRS7gRKmZ7w4VQRyl15GIpEn/IvXZpThvZTS/oKgX2ryKwydxvBCVO0qXmbE7fMyRQCu56EmPmJPnJF6g7m74eMBlhShCyauinjZH7nT89XUIwRxPaQRpanNFGs7/aZf0JmW02sX1GU/CzAUFgGpH/qoZsmcZb7qEwuJEC2+rdl5zRm37uifo8ZuA/Unmx5E0HPlNnT6dzg+pA6sx7kERpDcdo883ej7As1lVD9y41kTrH1Tq3uMRzo4Y8fDDaKvnmT/Zczor4Kn1QFAIvrQjnuKbtWPXoU9rnyCJ6xHjb3IGZTA8K7uSw1R8MAiikxHleosLdNTHNmyWLJ9D6rExXj1nZ0OuvUEZ8RvPgRq+l1a9lqIMZ/rM/hI7WXYZwR3hP9zYEQih2GVm1uxmPOmhLUO9MY2Lz6liIFiJ5rnydR3j2bevNNVGZUliaL0bkzNbxNrWnT6dN82TENB+bHbA8Z2WFGjOTsy9/vQrBPFG/yIVSYGPG9J60q596ge+otrrAMTTgyCogALIIEluhXkfJmBwyJGgFrZUNoRGMiMnoIVFQlDKKUmqdS8s2XJA9LIApDlkpCuFukGfaNuRA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
