travis:
  secure:
    BINSTAR_TOKEN: JY+8wP+SocmV2gsauG/QxV2E4N8LsVabj1uZUeREqZrRWLufwdIGZ9EhbV3K9CUt1ESgoskIMpbQYdq+u4yXlGyp8aMudqpxOs/9c/PgY8AMBv1pbJbVJ/gIHpWlB/tpRm3g+qTRyH4EOhCgMaCH3Udenm+Jmctuu40NTfrhNNeYXQbSmkqCGcORp295tEpFcewfOSTXvoJTCX8C4azab1tB7ICMYr+4uQGU7S15vD7vgLZ/twSo+NVpKIV1Aq5dw1a0X+S98aXX3A8zcINpUUF5ZoPkSOo7qavEMVRLm4fE2MtiTz5hiZo90AZlC8yleyTwxEgCyHIcAWWeppaywr7iWulC6beP4YihNvaraoqcIy/mSz4yfPH/TDFkf6QEd21Pcj8Pg3Kch/qsU4FaMs4INHVQcKeknyY13++0gm7e2C7PYIyrtDnemPcqF6KJdW1eHLuCS3CMEby4YPJ8AhHZnZu3WiIQ078y2jrqLW8t0lAiKR0SRMn0P7O0INVDNTS/WAZNXL3wGB6MkPKhgUtTHtMHa40vxUij99Wz18SwBRy+xksJpEPL2SNQg+VeOsYxIh4T6ZRUMAYjy7naf7fmAmjI8FMsKneP2rPHDx6wzxjsa5BPiC0jH12Ge00CJcuKf3O3MEQaOU1lDRRUucrLsYkUn9mqrL3ssSR0IFY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
