travis:
  secure:
    BINSTAR_TOKEN: DCxRaYgIp4nHX2EYuAvxwbhmWr5XgRTpby7eVRTj7ADnq9AZbSgEAp4AntLtJxVrhX3+mgAOGkQLZ246iMWA5eoVLMoC5zCyRaEMum/aM55vGSgjI7bCH8VKOuC1iMugRkyfNn/M7FCEgwMd1LoVbT9isne7+50DzPJLkUQ1+X4LxOW6yrz38+z9LyH/OZ64MY751GrnnvNeVwScCvqyGSvTn/RoNCpubpBQeuwTFLa/EdzAhoCyYNzEW+vQIsMwTnLeGQX/aZcFK0zMxAPOqJfB4j8JoJ84HMEY97cVyndFjfnEvwEiJjz3U7NvJw1nS5PHU9ckHzoPXd7b0oWyVoMV4G0l9Qj2su+qbEs582iHKo7fDe7ot9ZwHTvij8kW+hsmcC7RclZZOhH17Y5YZyc2R5XB5pPgxO1PNh5pSYMYMljlgZQa/BA5kJCSFMcLaxlbi6dXWjyOYtvzDJEJkwnoS1UPFGGhCCg0LfgrhfYqv03ZTlzPHA3maYDTQRmDj1fvlNGs+/ObF4cftI2v27H4zNL36mzU31+pIvP25UH4p5KA9Igz3vsnw4kVVNIOW+a0r2aOxLudtJwX324ZbZGnPZIwHBBhbPnEMMXR4GSPj/lZqNeKnfvvrB6Oiu2ismu2krgUwEEfje8TgHYAfwjJ9hGNQTS9s0t514qsX9M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
